In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## sentences 

sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
       'your videos are good']



In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size

voc_size = 10000

In [6]:
## One Hot Representation for every word

one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5598, 6835, 3342, 9161],
 [5598, 6835, 3342, 8353],
 [5598, 8886, 3342, 1891],
 [4707, 3331, 3088, 2640, 7080],
 [4707, 3331, 3088, 2640, 939],
 [1694, 5598, 5400, 3342, 9744],
 [205, 8148, 1626, 2640]]

In [8]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 8  ## to keep all the sentences of same size
embedded_docs = pad_sequences(one_hot_repr , padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5598 6835 3342 9161]
 [   0    0    0    0 5598 6835 3342 8353]
 [   0    0    0    0 5598 8886 3342 1891]
 [   0    0    0 4707 3331 3088 2640 7080]
 [   0    0    0 4707 3331 3088 2640  939]
 [   0    0    0 1694 5598 5400 3342 9744]
 [   0    0    0    0  205 8148 1626 2640]]


In [11]:
## Feature Representation
dimension = 10

In [13]:
model = Sequential()
model.add(Embedding(voc_size , dimension , input_length = sent_length))
model.compile("adam","mse")


In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 237ms/step


array([[[-1.49940476e-02,  4.15012576e-02, -2.35079601e-03,
          3.60309742e-02, -1.35935843e-04, -3.07178739e-02,
         -3.65115702e-04, -4.85832579e-02, -2.91490555e-02,
          9.78211313e-03],
        [-1.49940476e-02,  4.15012576e-02, -2.35079601e-03,
          3.60309742e-02, -1.35935843e-04, -3.07178739e-02,
         -3.65115702e-04, -4.85832579e-02, -2.91490555e-02,
          9.78211313e-03],
        [-1.49940476e-02,  4.15012576e-02, -2.35079601e-03,
          3.60309742e-02, -1.35935843e-04, -3.07178739e-02,
         -3.65115702e-04, -4.85832579e-02, -2.91490555e-02,
          9.78211313e-03],
        [-1.49940476e-02,  4.15012576e-02, -2.35079601e-03,
          3.60309742e-02, -1.35935843e-04, -3.07178739e-02,
         -3.65115702e-04, -4.85832579e-02, -2.91490555e-02,
          9.78211313e-03],
        [ 3.70370857e-02,  9.58490372e-03, -4.04025689e-02,
         -9.31022316e-03,  2.17946619e-03, -2.41676923e-02,
          4.07430567e-02, -1.40811801e-02, -3.035567